version: '3.0'

services:

  latest:
    build:
      args:
        branch: master
        ignition_codename: citadel
        pypi_package: gym-ignition
      context: .
      dockerfile: Dockerfile.latest
    image: diegoferigo/gym-ignition:latest

  nightly:
    build:
      args:
        branch: devel
        ignition_codename: citadel
        pypi_package: gym-ignition-nightly
      context: .
      dockerfile: Dockerfile.nightly
    image: diegoferigo/gym-ignition:nightly

  ci-master:
    build:
      args:
        from: ubuntu:bionic
        BUILD_SHARED_LIBS: "ON"
        CMAKE_BUILD_TYPE: Debug
      context: .
      dockerfile: Dockerfile.cicd-master
    image: diegoferigo/gym-ignition:ci-master

  pypi-master:
    build:
      args:
        from: ubuntu:bionic
        BUILD_SHARED_LIBS: "OFF"
        CMAKE_BUILD_TYPE: Release
      context: .
      dockerfile: Dockerfile.cicd-master
    image: diegoferigo/gym-ignition:pypi-master

  ci-devel:
    build:
      args:
        from: ubuntu:bionic
        BUILD_SHARED_LIBS: "ON"
        CMAKE_BUILD_TYPE: Debug
      context: .
      dockerfile: Dockerfile.cicd-devel
    image: diegoferigo/gym-ignition:ci-devel

  pypi-devel:
    build:
      args:
        from: ubuntu:bionic
        BUILD_SHARED_LIBS: "OFF"
        CMAKE_BUILD_TYPE: Release
      context: .
      dockerfile: Dockerfile.cicd-devel
    image: diegoferigo/gym-ignition:pypi-devel
