version: '3.0'

services:

  base:
    build:
      args:
        from: ubuntu:focal
      context: .
      dockerfile: base.Dockerfile
    image: diegoferigo/gym-ignition:base

  # ======
  # MASTER
  # ======

  ci-master:
    build:
      args:
        from: diegoferigo/gym-ignition:base
        ignition_codename: citadel
      context: .
      dockerfile: Dockerfile.cicd-master
    image: diegoferigo/gym-ignition:ci-master

  pypi-master:
    build:
      args:
        from: diegoferigo/gym-ignition:base
        ignition_codename: citadel
      context: .
      dockerfile: Dockerfile.cicd-master
    image: diegoferigo/gym-ignition:pypi-master

  # =====
  # DEVEL
  # =====

  ci-devel:
    build:
      args:
        from: diegoferigo/gym-ignition:base
        ignition_codename: citadel
        CMAKE_BUILD_TYPE: Debug
      context: .
      dockerfile: Dockerfile.cicd-devel
    image: diegoferigo/gym-ignition:ci-devel

  pypi-devel:
    build:
      args:
        from: diegoferigo/gym-ignition:base
        ignition_codename: citadel
        CMAKE_BUILD_TYPE: Release
      context: .
      dockerfile: Dockerfile.cicd-devel
    image: diegoferigo/gym-ignition:pypi-devel

  # ====
  # DEMO
  # ====

  latest:
    build:
      args:
        from: diegoferigo/gym-ignition:pypi-master
        branch: master
        pypi_package: gym-ignition
      context: .
      dockerfile: Dockerfile
    image: diegoferigo/gym-ignition:latest

  nightly:
    build:
      args:
        from: diegoferigo/gym-ignition:ci-devel
        branch: devel
        pypi_package: gym-ignition-nightly
      context: .
      dockerfile: Dockerfile
    image: diegoferigo/gym-ignition:nightly
