name: 'CI Docker Image'

on:
  push:
    paths:
      - ".ci/*"
      - ".github/workflows/docker.yml"
  schedule:
    # Execute a weekly build on Monday at 2AM UTC
    - cron:  '0 2 * * 1'

jobs:

  docker:
    name: 'Image diegoferigo/gym-ignition:ci'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseimage: ['ubuntu:bionic']

    steps:
      - uses: actions/checkout@master

      - name: 'Build'
        run: |
          cd .ci
          docker build \
            --pull --build-arg from=${{ matrix.baseimage }} \
            --rm -t diegoferigo/gym-ignition:ci .

      - name: Login
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Push
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master'
        run: docker push diegoferigo/gym-ignition:ci
