name: Docker Images

on:
  push:
    paths:
      - ".docker/*"
      - ".github/workflows/docker.yml"
  pull_request:
    paths:
      - ".docker/*"
      - ".github/workflows/docker.yml"
  schedule:
    # Execute a weekly build on Monday at 2AM UTC
    - cron:  '0 2 * * 1'

jobs:
  docker:
    name: 'diegoferigo/gym-ignition:${{ matrix.tag }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        baseimage: ['ubuntu:bionic']
        tag:
          - ci
          - pypi
          - latest
          - nightly
        include:
          - tag: nightly
            extra_docker_options: "--build-arg pypi_package='gym-ignition-nightly'"

    steps:
      - uses: actions/checkout@master

      - name: Build
        run: |
          cd .docker/
          docker build . \
            --pull --build-arg from=${{ matrix.baseimage }} \
            --rm -t diegoferigo/gym-ignition:${{ matrix.tag }} \
            ${{ matrix.extra_docker_options }} \
            -f Dockerfile.${{ matrix.tag }}

      - name: Login
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/devel')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin

      - name: Push
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/master' &&
          matrix.tag != 'nightly'
        run: docker push diegoferigo/gym-ignition:${{ matrix.tag }}

      - name: Push nightly
        if: |
          github.repository == 'robotology/gym-ignition' &&
          github.event_name != 'pull_request' &&
          github.ref == 'refs/heads/devel' &&
          matrix.tag == 'nightly'
        run: docker push diegoferigo/gym-ignition:${{ matrix.tag }}
